#ifndef ERROR_CODE_H
#define ERROR_CODE_H

typedef enum {
    ERR_OK,
    ERR_NULL_ARGUMENT,
    ERR_INVALID_ARGUMENT,
    ERR_OUT_OF_MEMORY,
    ERR_FILE_OPEN,
    ERR_FILE_READ,
    ERR_CONFIG_SYNTAX,
    ERR_CONFIG_VALUE,
    ERR_CONFIG_MISSING,
    ERR_SUBSCRIBERS_FULL,
    ERR_QUEUE_FULL,
    ERR_NOT_IN_QUEUE,
    ERR_CHARGER_BUSY,
    ERR_INCOMPATIBLE
} ErrorCode;

#endif //ERROR_CODE_H
